theme: jekyll-theme-minimal
title: Sujal Chauhan, PMPÂ®
description: Project Manager | Business Process Optimization | Cloud Transformation

# The / helps the browser find the file in the root folder
logo: /Sujal-Profile.jpg

# This hides the ugly "Download ZIP" buttons
show_downloads: false

google_analytics:
