theme: jekyll-theme-minimal
title: Sujal Chauhan, PMPÂ®
description: Project Manager | Business Process Optimization | Cloud Transformation

# Updated to match your new filename
logo: Sujal-Profile.jpg

show_downloads: true
google_analytics:
