theme: jekyll-theme-minimal
title: Sujal Chauhan, PMPÂ®
description: Project Manager | Business Process Optimization | Cloud Transformation

# This puts your photo in the sidebar
logo: /profile.jpg  
# (Make sure your uploaded photo name matches exactly!)

show_downloads: true
google_analytics:
